// Autogenerated from Pigeon (v1.0.8), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import <Foundation/Foundation.h>
@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

typedef NS_ENUM(NSUInteger, FLTRequsetType) {
  FLTRequsetTypeSayhello = 0,
  FLTRequsetTypeGetbattery = 1,
};

@class FLTSearchRequest;
@class FLTSearchReply;

@interface FLTSearchRequest : NSObject
@property(nonatomic, assign) FLTRequsetType query;
@end

@interface FLTSearchReply : NSObject
@property(nonatomic, copy, nullable) NSString * result;
@end

/// The codec used by FLTSearchApi.
NSObject<FlutterMessageCodec> *FLTSearchApiGetCodec(void);

@protocol FLTSearchApi
- (nullable FLTSearchReply *)searchRequest:(FLTSearchRequest *)request error:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void FLTSearchApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<FLTSearchApi> *_Nullable api);

NS_ASSUME_NONNULL_END
